language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
compiler:
  - gcc
  - clang
before_install:
  if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
script:
  make
