language: cpp
env:
  matrix:
  - COMPILER=g++-4.8
  - COMPILER=g++-4.9
  - COMPILER=clang++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.9
compiler:
  - gcc
  - clang
script:
  make CXX=$COMPILER -j2
