language: cpp
env:
  matrix:
  - COMPILER=g++-4.7
  - COMPILER=g++-4.8
  - COMPILER=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.7
    - g++-4.8
    - g++-4.9
script:
  make CXX=$COMPILER -j2
