language: android
sudo: false
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-23
  licenses:
    - '.+'
before_script:
  - export TERM=dumb
  - curl -L http://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -O
  - unzip -q android-ndk-r10e-linux-x86_64.zip
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export LOCAL_ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
  - export LOCAL_ANDROID_NDK_HOST_PLATFORM="linux-x86_64"
  - export PATH=$PATH:${ANDROID_NDK_HOME}
  - export _NO_CHECK_SIGNATURE=true
script:
  - cmake -DANDROID_NDK=/path/to/android-ndk -DPEGTL_PLATFORM=Android
  - make
  - make test
  - run-on-android.sh
