version: '{branch}-{build}'

os: Visual Studio 2015

configuration: Release

branches:
  only:
    - master

init: []

build_script:
- cmd: cmake -Wno-dev . -G "Visual Studio 14 2015"
- cmd: cmake -Wno-dev --build . --config Release

test_script:
- cmd: ctest -Wno-dev -C Release -V

install: []
