version: '{branch}-{build}'

os: Visual Studio 2015

configuration: Release

branches:
  only:
    - master

init: []

build_script:
- md build-vc
- cd build-vc
- cmake -Wno-dev ..
- cmd: make all

test_script:
- cmd: make test

install: []
